server:
  port: 82

spring:
  application:
    name: 测试Demo

  thymeleaf:
    cache: false # 关闭缓存

demo:
  custCode: EVK1WTN0EKABOJ6RK3Z0
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLntmKpma0GbHXD6HG6uXl7UYyre9Gg8T4dXEvETeRKP/mtNNCLSq0Iny3XCxlSbit+vG69rrQmGlM5okfPkLYFqwhgip5u74fTcmxaqiH2X9LV85NKPQozim4fnkbvfdTqjLNoBsMLcsg/cdl9at7A6gMonbCAA8w6wpxQfiMAwIDAQAB
  payUrl: http://localhost:8080/order/create
  behalfpayUrl: http://localhost:8080/behalfpay/create
